// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-s2pxw7iG8EaSPvXrszUEYMaGnlUV9ws',
    appId: '1:324378386655:web:26658b1be72a25f95a096a',
    messagingSenderId: '324378386655',
    projectId: 'vitap-5ff25',
    authDomain: 'vitap-5ff25.firebaseapp.com',
    storageBucket: 'vitap-5ff25.appspot.com',
    measurementId: 'G-KYJ28Q75M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQHl1XRweSPvsvVMN--xjNE28Clgo2b0',
    appId: '1:324378386655:android:1f50129a03ed560a5a096a',
    messagingSenderId: '324378386655',
    projectId: 'vitap-5ff25',
    storageBucket: 'vitap-5ff25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPysPnIPnJYPCtYbpg4bzOduJdRA6rLo',
    appId: '1:324378386655:ios:b4fa6516c440ddfd5a096a',
    messagingSenderId: '324378386655',
    projectId: 'vitap-5ff25',
    storageBucket: 'vitap-5ff25.appspot.com',
    iosBundleId: 'com.example.vitAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPysPnIPnJYPCtYbpg4bzOduJdRA6rLo',
    appId: '1:324378386655:ios:b4fa6516c440ddfd5a096a',
    messagingSenderId: '324378386655',
    projectId: 'vitap-5ff25',
    storageBucket: 'vitap-5ff25.appspot.com',
    iosBundleId: 'com.example.vitAp',
  );
}
